apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jznhkydz3-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jznhkydz3-java-springboot-gitops